--------------------------------------------------------
--  File created - Pazartesi-Kasým-30-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table BOLUM_SIRALAMA
--------------------------------------------------------

  CREATE TABLE "UNIVERLIST"."BOLUM_SIRALAMA" 
   (	"BÖLÜM_SIRALAMASI" NUMBER(*,0), 
	"BÖLÜM_GENEL_SIRALAMASI" VARCHAR2(128 BYTE), 
	"BÖLÜM_PUANI" NUMBER(38,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into UNIVERLIST.BOLUM_SIRALAMA
SET DEFINE OFF;
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('1','Týp','99,54');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('2','Diþ Hekimliði','82,64');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('3','Bilgisayar Mühendisliði','76,89');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('4','Eczacýlýk','73,54');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('5','Fizyoterapi ve Rehabilitasyon','73,42');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('6','Elektrik Mühendisliði','73,1');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('7','Elektronik Mühendisliði','71,63');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('8','Elektronik ve Haberleþme Mühendisliði','71,42');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('9','Endüstri Mühendisliði','71,22');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('10','Veterinerlik','68,5');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('11','Elektrik-Elektronik Mühendisliði','67,56');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('12','Psikolojik Danýþmanlýk ve Rehberlik','67,2');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('13','Ýnþaat Mühendisliði','66,91');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('14','Makine Mühendisliði','65,35');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('15','Ýç Mimarlýk','64,83');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('16','Geomatik (Harita) Mühendisliði','63,12');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('17','Mimarlýk','62,66');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('18','Maden Mühendisliði','61,7');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('19','Mekatronik Mühendisliði','60,82');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('20','Hukuk','60');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('21','Psikoloji','59,44');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('22','Metalurji ve Malzeme Mühendisliði','59,42');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('23','Hemþirelik','59');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('24','Kimya Mühendisliði','55,76');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('25','Þehir ve Bölge Planlama','55,24');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('26','Siyaset Bilimi ve Uluslararasý Ýliþkiler','54,02');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('27','Dil ve Edebiyat','53,74');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('28','Uluslararasý Ýliþkiler','53,11');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('29','Beslenme Diyetetik','52,15');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('30','Ýlahiyat','51,51');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('31','Ýstatistik','51,09');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('32','Ýþletme','50,56');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('33','Öðretmenlik Programlarý','50,4');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('34','Gýda Mühendisliði','49,21');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('35','Matematik','49,2');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('36','Bankacýlýk ve Finans','48,49');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('37','Jeoloji Mühendisliði','48,49');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('38','Kimya','47,68');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('39','Fizik','47,41');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('40','Ýktisat','47,41');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('41','Çevre Mühendisliði','47,3');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('42','Tekstil Mühendisliði','46,22');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('43','Siyaset Bilimi ve Kamu Yönetimi','46,07');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('44','Turizm ve Otel Ýþletmeciliði','45,03');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('45','Ekonometri','44,46');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('46','Sosyoloji','44,21');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('47','Halkla Ýliþkiler','43,3');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('48','Çalýþma Ekonomisi ve Endüstri Ýliþkileri','42,59');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('49','Maliye','42,05');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('50','Kamu Yönetimi','42,04');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('51','Ýletiþim','40,13');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('52','Biyoloji','40');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('53','Radyo, Televizyon Ve Sinema','39,52');
Insert into UNIVERLIST.BOLUM_SIRALAMA ("BÖLÜM_SIRALAMASI","BÖLÜM_GENEL_SIRALAMASI","BÖLÜM_PUANI") values ('54','Felsefe','34,28');
--------------------------------------------------------
--  DDL for Index BLM_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIVERLIST"."BLM_ID" ON "UNIVERLIST"."BOLUM_SIRALAMA" ("BÖLÜM_SIRALAMASI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table BOLUM_SIRALAMA
--------------------------------------------------------

  ALTER TABLE "UNIVERLIST"."BOLUM_SIRALAMA" MODIFY ("BÖLÜM_SIRALAMASI" NOT NULL ENABLE);
  ALTER TABLE "UNIVERLIST"."BOLUM_SIRALAMA" ADD CONSTRAINT "BLM_ID" PRIMARY KEY ("BÖLÜM_SIRALAMASI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
