--------------------------------------------------------
--  File created - Pazartesi-Kasým-30-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DEVLET_UNI_SIRALAMA
--------------------------------------------------------

  CREATE TABLE "UNIVERLIST"."DEVLET_UNI_SIRALAMA" 
   (	"ÜNÝVERSÝTE_SIRALAMASI" NUMBER(*,0), 
	"DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI" VARCHAR2(128 BYTE), 
	"ÜNÝVERSÝTE_PUANI" NUMBER(38,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into UNIVERLIST.DEVLET_UNI_SIRALAMA
SET DEFINE OFF;
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('1','Orta Doðu Teknik Üniversitesi','98,15');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('2','Boðaziçi Üniversitesi','91,28');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('3','Ýstanbul Teknik Üniversitesi','86,91');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('4','Yýldýz Teknik Üniversitesi','74,03');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('5','Gebze Teknik Üniversitesi','72,08');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('6','Hacettepe Üniversitesi','69,48');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('7','Ýzmir Yüksek Teknoloji Enstitüsü','66,51');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('8','Ege Üniversitesi','64,75');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('9','Karadeniz Teknik Üniversitesi','63,56');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('10','Ýstanbul Üniversitesi','63,41');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('11','Gazi Üniversitesi','62,08');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('12','Çukurova Üniversitesi','60,67');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('13','Dokuz Eylül Üniversitesi','59,89');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('14','Gaziantep Üniversitesi','59,77');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('15','Mimar Sinan Güzel Sanatlar Üniversitesi','59,58');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('16','Akdeniz Üniversitesi','59,55');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('17','Marmara Üniversitesi','59,23');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('18','Sakarya Üniversitesi','59,04');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('19','Kocaeli Üniversitesi','59,02');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('20','Anadolu Üniversitesi','58,15');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('21','Muðla Sýtký Koçman Üniversitesi','57,71');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('22','Eskiþehir Osmangazi Üniversitesi','57,3');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('23','Selçuk Üniversitesi','57,29');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('24','Ankara Üniversitesi','57,16');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('25','Atatürk Üniversitesi','56,49');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('26','Erciyes Üniversitesi','55,41');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('27','Ondokuz Mayýs Üniversitesi','55,34');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('28','Niðde Ömer Halisdemir Üniversitesi','55,17');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('29','Süleyman Demirel Üniversitesi','55,17');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('30','Ýnönü Üniversitesi','54,86');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('31','Abant Ýzzet Baysal Üniversitesi','54,86');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('32','Uludað Üniversitesi','54,11');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('33','Trakya Üniversitesi','53,88');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('34','Adýyaman Üniversitesi','53,8');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('35','Pamukkale Üniversitesi','53,55');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('36','Fýrat Üniversitesi','53,37');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('37','Dicle Üniversitesi','52,96');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('38','Çanakkale Onsekiz Mart Üniversitesi','52,39');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('39','Bülent Ecevit Üniversitesi','52,32');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('40','Karabük Üniversitesi','51,56');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('41','Yalova Üniversitesi','50,96');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('42','Harran Üniversitesi','50,21');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('43','Gümüþhane Üniversitesi','50,14');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('44','Cumhuriyet Üniversitesi','49,9');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('45','Recep Tayyip Erdoðan Üniversitesi','49,49');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('46','Artvin Çoruh Üniversitesi','49,32');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('47','Dumlupýnar Üniversitesi','48,76');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('48','Balýkesir Üniversitesi','48,6');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('49','Celâl Bayar Üniversitesi','48,48');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('50','Bozok Üniversitesi','47,45');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('51','Kahramanmaraþ Sütçü Ýmam Üniversitesi','47,34');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('52','Afyon Kocatepe Üniversitesi','46,91');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('53','Aksaray Üniversitesi','46,84');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('54','Kýrýkkale Üniversitesi','46,69');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('55','Erzincan Üniversitesi','46,05');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('56','Bilecik Þeyh Edebali Üniversitesi','45,65');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('57','Adnan Menderes Üniversitesi','45,48');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('58','Uþak Üniversitesi','45,26');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('59','Gaziosmanpaþa Üniversitesi','44,46');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('60','Giresun Üniversitesi','44,09');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('61','Nevþehir Hacý Bektaþ Veli Üniversitesi','41,28');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('62','Ordu Üniversitesi','41,27');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('63','Bingöl Üniversitesi','40,58');
Insert into UNIVERLIST.DEVLET_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","DEVLET_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('64','Kastamonu Üniversitesi','39,34');
--------------------------------------------------------
--  DDL for Index DEVLET_UNI_SIRALAMA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIVERLIST"."DEVLET_UNI_SIRALAMA_PK" ON "UNIVERLIST"."DEVLET_UNI_SIRALAMA" ("ÜNÝVERSÝTE_SIRALAMASI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DEVLET_UNI_SIRALAMA
--------------------------------------------------------

  ALTER TABLE "UNIVERLIST"."DEVLET_UNI_SIRALAMA" MODIFY ("ÜNÝVERSÝTE_SIRALAMASI" NOT NULL ENABLE);
  ALTER TABLE "UNIVERLIST"."DEVLET_UNI_SIRALAMA" ADD CONSTRAINT "DEVLET_UNI_SIRALAMA_PK" PRIMARY KEY ("ÜNÝVERSÝTE_SIRALAMASI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
