--------------------------------------------------------
--  File created - Pazartesi-Kasým-30-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM
--------------------------------------------------------

  CREATE TABLE "UNIVERLIST"."MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM" 
   (	"BÖLÜM_SIRALAMASI" NUMBER(*,0), 
	"MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER" VARCHAR2(128 BYTE), 
	"BÖLÜM_PUANI" NUMBER(38,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM
SET DEFINE OFF;
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('1','Týp','100');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('2','Elektronik Mühendisliði','86,08');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('3','Bilgisayar Mühendisliði','84,95');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('4','Elektrik Mühendisliði','77,36');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('5','Diþ Hekimliði','76,99');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('6','Ýnþaat Mühendisliði','73,36');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('7','Elektronik ve Haberleþme Mühendisliði','70,57');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('8','Endüstri Mühendisliði','69,14');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('9','Fizyoterapi ve Rehabilitasyon','69,13');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('10','Veterinerlik','67,76');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('11','Eczacýlýk','67,76');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('12','Elektrik-Elektronik Mühendisliði','67,76');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('13','Geomatik (Harita) Mühendisliði','67,13');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('14','Ýç Mimarlýk','66,77');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('15','Makine Mühendisliði','64,27');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('16','Mimarlýk','61,93');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('17','Hemþirelik','60,95');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('18','Maden Mühendisliði','59,32');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('19','Psikolojik Danýþmanlýk ve Rehberlik','57,51');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('20','Mekatronik Mühendisliði','56,11');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('21','Hukuk','53,4');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('22','Metalurji ve Malzeme Mühendisliði','52,16');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('23','Þehir ve Bölge Planlama','49,91');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('24','Kimya Mühendisliði','47,74');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('25','Psikoloji','47,74');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('26','Tekstil Mühendisliði','46,07');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('27','Gýda Mühendisliði','45,06');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('28','Dil ve Edebiyat','42,89');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('29','Ýþletme','41,03');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('30','Jeoloji Mühendisliði','40,36');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('31','Turizm ve Otel Ýþletmeciliði','40,35');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('32','Ýstatistik','40,2');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('33','Matematik','39,77');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('34','Çevre Mühendisliði','39,32');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('35','Bankacýlýk ve Finans','38,9');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('36','Beslenme Diyetetik','38,37');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('37','Uluslararasý Ýliþkiler','37,25');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('38','Siyaset Bilimi ve Uluslararasý Ýliþkiler','37,01');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('39','Fizik','36,96');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('40','Öðretmenlik Programlarý','36,41');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('41','Kimya','35,85');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('42','Ýlahiyat','35,42');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('43','Ýktisat','34,31');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('44','Halkla Ýliþkiler','32,64');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('45','Ekonometri','30,57');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('46','Siyaset Bilimi ve Kamu Yönetimi','27,65');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('47','Ýletiþim','27,32');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('48','Radyo, Televizyon Ve Sinema','26,55');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('49','Maliye','25,11');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('50','Çalýþma Ekonomisi ve Endüstri Ýliþkileri','24,22');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('51','Kamu Yönetimi','23,37');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('52','Sosyoloji','23,29');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('53','Biyoloji','22,44');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_BÖLÜMLER","BÖLÜM_PUANI") values ('54','Felsefe','15,78');
--------------------------------------------------------
--  Constraints for Table MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM
--------------------------------------------------------

  ALTER TABLE "UNIVERLIST"."MEZUNLARIN_EN_HIZLI_IS_BULAN_BOLUM" MODIFY ("BÖLÜM_SIRALAMASI" NOT NULL ENABLE);
