--------------------------------------------------------
--  File created - Pazartesi-Kasým-30-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI
--------------------------------------------------------

  CREATE TABLE "UNIVERLIST"."MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI" 
   (	"ÜNÝVERSÝTE_SIRALAMASI" NUMBER(*,0), 
	"MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER" VARCHAR2(128 BYTE), 
	"ÜNÝVERSÝTE_PUANI" NUMBER(38,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI
SET DEFINE OFF;
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('1','Özyeðin Üniversitesi','100');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('2','Orta Doðu Teknik Üniversitesi','92,69');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('3','Boðaziçi Üniversitesi','86,98');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('4','Ýstanbul Teknik Üniversitesi','86,77');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('5','Koç Üniversitesi','85,74');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('6','Sabancý Üniversitesi','84,31');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('7','Gebze Teknik Üniversitesi','78,58');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('8','Yeditepe Üniversitesi','74,25');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('9','Tobb Ekonomi Ve Teknoloji Üniversitesi','74,05');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('10','Hasan Kalyoncu Üniversitesi','72,7');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('11','Acýbadem Üniversitesi','70,51');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('12','Yýldýz Teknik Üniversitesi','68,21');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('13','Ýhsan Doðramacý Bilkent Üniversitesi','63,22');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('14','Okan Üniversitesi','61,11');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('15','Bahçeþehir Üniversitesi','59,5');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('16','Ýzmir Yüksek Teknoloji Enstitüsü','58,71');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('17','Gaziantep Üniversitesi','56,83');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('18','Yaþar Üniversitesi','53,18');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('19','Kadir Has Üniversitesi','53,16');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('20','Kocaeli Üniversitesi','53,12');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('21','Karadeniz Teknik Üniversitesi','53,1');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('22','Doðuþ Üniversitesi','51,14');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('23','Ýstanbul Üniversitesi','50,71');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('24','Gazi Üniversitesi','50,07');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('25','Ýstanbul Bilgi Üniversitesi','49,38');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('26','Marmara Üniversitesi','49,17');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('27','Ege Üniversitesi','48,8');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('28','Hacettepe Üniversitesi','48,69');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('29','Mimar Sinan Güzel Sanatlar Üniversitesi','47,21');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('30','Dokuz Eylül Üniversitesi','46,39');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('31','Çankaya Üniversitesi','45,95');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('32','Muðla Sýtký Koçman Üniversitesi','45,86');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('33','Selçuk Üniversitesi','44,58');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('34','Ýzmir Ekonomi Üniversitesi','44,02');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('35','Karabük Üniversitesi','43,45');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('36','Eskiþehir Osmangazi Üniversitesi','43,39');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('37','Çukurova Üniversitesi','43,35');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('38','Ýstanbul Ticaret Üniversitesi','43,32');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('39','Sakarya Üniversitesi','43,01');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('40','Akdeniz Üniversitesi','42,96');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('42','Trakya Üniversitesi','42,96');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('41','Dicle Üniversitesi','42,85');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('43','Anadolu Üniversitesi','42,32');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('44','Niðde Ömer Halisdemir Üniversitesi','42,28');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('45','Abant Ýzzet Baysal Üniversitesi','42,25');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('46','Gümüþhane Üniversitesi','41,44');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('47','Fýrat Üniversitesi','41,19');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('48','Erciyes Üniversitesi','40,38');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('49','Beykent Üniversitesi','40,16');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('50','Balýkesir Üniversitesi','40,08');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('51','Ýstanbul Arel Üniversitesi','40,01');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('52','Bülent Ecevit Üniversitesi','39,83');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('53','Yalova Üniversitesi','39,42');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('54','Cumhuriyet Üniversitesi','39,15');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('55','Bozok Üniversitesi','39,11');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('56','Ondokuz Mayýs Üniversitesi','38,83');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('57','Uludað Üniversitesi','38,63');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('58','Pamukkale Üniversitesi','38,54');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('59','Celâl Bayar Üniversitesi','37,81');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('60','Ýstanbul Aydýn Üniversitesi','37,58');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('61','Süleyman Demirel Üniversitesi','37,45');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('62','Ýstanbul Kültür Üniversitesi','37,25');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('63','Kahramanmaraþ Sütçü Ýmam Üniversitesi','37,2');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('64','Harran Üniversitesi','37,01');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('65','Adýyaman Üniversitesi','36,96');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('66','Atatürk Üniversitesi','36,33');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('67','Ankara Üniversitesi','35,42');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('68','Kýrýkkale Üniversitesi','35,15');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('69','Afyon Kocatepe Üniversitesi','34,88');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('70','Ýnönü Üniversitesi','33,28');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('71','Bilecik Þeyh Edebali Üniversitesi','33,2');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('72','Erzincan Üniversitesi','33,16');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('73','Dumlupýnar Üniversitesi','32,78');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('74','Çanakkale Onsekiz Mart Üniversitesi','31,58');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('75','Aksaray Üniversitesi','30,68');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('76','Ordu Üniversitesi','29,12');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('77','Giresun Üniversitesi','26,52');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('78','Adnan Menderes Üniversitesi','26,49');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('79','Uþak Üniversitesi','26,39');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('80','Gaziosmanpaþa Üniversitesi','26,15');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('81','Bingöl Üniversitesi','26,06');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('82','Artvin Çoruh Üniversitesi','25,38');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('83','Recep Tayyip Erdoðan Üniversitesi','22,36');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('84','Kastamonu Üniversitesi','21,69');
Insert into UNIVERLIST.MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI ("ÜNÝVERSÝTE_SIRALAMASI","MEZUNLARI_EN_HIZLI_ÝÞ_BULAN_ÜNÝVERSÝTELER","ÜNÝVERSÝTE_PUANI") values ('85','Nevþehir Hacý Bektaþ Veli Üniversitesi','20,19');
--------------------------------------------------------
--  Constraints for Table MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI
--------------------------------------------------------

  ALTER TABLE "UNIVERLIST"."MEZUNLARIN_EN_HIZLI_IS_BULAN_UNI" MODIFY ("ÜNÝVERSÝTE_SIRALAMASI" NOT NULL ENABLE);
