--------------------------------------------------------
--  File created - Pazartesi-Kasým-30-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table ARASTIRMA_UNI_SIRALAMA
--------------------------------------------------------

  CREATE TABLE "UNIVERLIST"."ARASTIRMA_UNI_SIRALAMA" 
   (	"ÜNÝVERSÝTE_SIRALAMASI" NUMBER(*,0), 
	"ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI" VARCHAR2(128 BYTE), 
	"ÜNÝVERSÝTE_PUANI" NUMBER(38,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA
SET DEFINE OFF;
Insert into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('1','Orta Doðu Teknik Üniversitesi','98,15');
Insert into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('2','Boðaziçi Üniversitesi','91,28');
Insert into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('3','Ýstanbul Teknik Üniversitesi','86,91');
Insert into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('4','Yýldýz Teknik Üniversitesi','74,03');
Insert into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('5','Gebze Teknik Üniversitesi','72,08');
Insert into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('6','Hacettepe Üniversitesi','69,48');
Insert into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('7','Ýzmir Yüksek Teknoloji Enstitüsü','66,51');
Insert into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('8','Ege Üniversitesi','64,75');
Insert into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('9','Ýstanbul Üniversitesi','63,41');
Insert into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('10','Gazi Üniversitesi','62,08');
Insert into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('11','Çukurova Üniversitesi','60,67');
Insert into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('12','Selçuk Üniversitesi','57,29');
Insert into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('13','Ankara Üniversitesi','57,16');
Insert into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('14','Erciyes Üniversitesi','55,41');
Insert into UNIVERLIST.ARASTIRMA_UNI_SIRALAMA ("ÜNÝVERSÝTE_SIRALAMASI","ARAÞTIRMA_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('15','Uludað Üniversitesi','54,11');
--------------------------------------------------------
--  Constraints for Table ARASTIRMA_UNI_SIRALAMA
--------------------------------------------------------

  ALTER TABLE "UNIVERLIST"."ARASTIRMA_UNI_SIRALAMA" MODIFY ("ÜNÝVERSÝTE_SIRALAMASI" NOT NULL ENABLE);
--------------------------------------------------------
--  Ref Constraints for Table ARASTIRMA_UNI_SIRALAMA
--------------------------------------------------------

  ALTER TABLE "UNIVERLIST"."ARASTIRMA_UNI_SIRALAMA" ADD CONSTRAINT "ARST_UNI_ID" FOREIGN KEY ("ÜNÝVERSÝTE_SIRALAMASI")
	  REFERENCES "UNIVERLIST"."DEVLET_UNI_SIRALAMA" ("ÜNÝVERSÝTE_SIRALAMASI") ENABLE;
