--------------------------------------------------------
--  File created - Pazartesi-Kasým-30-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table MEZUN_ISEBASLMA_BOLUM
--------------------------------------------------------

  CREATE TABLE "UNIVERLIST"."MEZUN_ISEBASLMA_BOLUM" 
   (	"BÖLÜM_SIRALAMASI" NUMBER(*,0), 
	"MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER" VARCHAR2(128 BYTE), 
	"BÖLÜM_PUANI" NUMBER(38,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM
SET DEFINE OFF;
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('1','Týp','100');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('2','Diþ Hekimliði','77,63');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('3','Fizyoterapi ve Rehabilitasyon','71,08');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('4','Eczacýlýk','59,31');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('5','Elektronik ve Haberleþme Mühendisliði','54,46');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('6','Bilgisayar Mühendisliði','51,01');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('7','Elektronik Mühendisliði','45,24');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('8','Elektrik Mühendisliði','45');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('9','Endüstri Mühendisliði','44,52');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('10','Psikolojik Danýþmanlýk ve Rehberlik','44,27');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('11','Elektrik-Elektronik Mühendisliði','42,27');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('12','Veterinerlik','40,5');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('13','Maden Mühendisliði','40,4');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('14','Mekatronik Mühendisliði','38,75');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('15','Ýnþaat Mühendisliði','38,1');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('16','Makine Mühendisliði','37,79');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('17','Geomatik (Harita) Mühendisliði','37,7');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('18','Metalurji ve Malzeme Mühendisliði','37,2');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('19','Beslenme Diyetetik','35,83');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('20','Kimya Mühendisliði','34,08');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('21','Uluslararasý Ýliþkiler','33,16');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('22','Mimarlýk','33,06');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('23','Siyaset Bilimi ve Uluslararasý Ýliþkiler','32,89');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('24','Hemþirelik','32,16');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('25','Ýç Mimarlýk','31,62');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('26','Psikoloji','30,91');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('27','Dil ve Edebiyat','30,2');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('28','Bankacýlýk ve Finans','30,05');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('29','Hukuk','28,45');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('30','Siyaset Bilimi ve Kamu Yönetimi','28,41');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('31','Þehir ve Bölge Planlama','27,96');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('32','Ýþletme','27,53');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('33','Kamu Yönetimi','27,27');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('34','Ýktisat','26,94');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('35','Ýstatistik','26,78');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('36','Öðretmenlik Programlarý','26,56');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('37','Ýlahiyat','26,48');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('38','Jeoloji Mühendisliði','24,53');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('39','Fizik','24,04');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('40','Gýda Mühendisliði','23,78');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('41','Matematik','22,48');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('42','Çevre Mühendisliði','22,43');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('43','Ekonometri','22,13');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('44','Kimya','21,27');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('45','Maliye','20,83');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('46','Çalýþma Ekonomisi ve Endüstri Ýliþkileri','19,61');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('47','Sosyoloji','19,01');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('48','Ýletiþim','17,68');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('49','Tekstil Mühendisliði','17,66');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('50','Turizm ve Otel Ýþletmeciliði','17,37');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('51','Biyoloji','17,11');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('52','Radyo, Televizyon Ve Sinema','15,77');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('53','Halkla Ýliþkiler','15,72');
Insert into UNIVERLIST.MEZUN_ISEBASLMA_BOLUM ("BÖLÜM_SIRALAMASI","MEZUNLARI_EN_YÜKSEK_ÜCRETLE_ÝÞE_BAÞLAYAN_BÖLÜMLER","BÖLÜM_PUANI") values ('54','Felsefe','9,13');
--------------------------------------------------------
--  Constraints for Table MEZUN_ISEBASLMA_BOLUM
--------------------------------------------------------

  ALTER TABLE "UNIVERLIST"."MEZUN_ISEBASLMA_BOLUM" MODIFY ("BÖLÜM_SIRALAMASI" NOT NULL ENABLE);
