--------------------------------------------------------
--  File created - Pazartesi-Kasým-30-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table VAKIF_UNI_SIRA
--------------------------------------------------------

  CREATE TABLE "UNIVERLIST"."VAKIF_UNI_SIRA" 
   (	"ÜNÝVERSÝTE_SIRALAMASI" NUMBER(*,0), 
	"VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI" VARCHAR2(128 BYTE), 
	"ÜNÝVERSÝTE_PUANI" NUMBER(38,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into UNIVERLIST.VAKIF_UNI_SIRA
SET DEFINE OFF;
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('1','Koç Üniversitesi','90,26');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('2','Sabancý Üniversitesi','89,29');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('3','Özyeðin Üniversitesi','89,22');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('4','Ýhsan Doðramacý Bilkent Üniversitesi','82,79');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('5','Tobb Ekonomi Ve Teknoloji Üniversitesi','78,09');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('6','Yeditepe Üniversitesi','72,97');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('7','Hasan Kalyoncu Üniversitesi','71,66');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('8','Acýbadem Üniversitesi','68,51');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('9','Bahçeþehir Üniversitesi','67,02');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('10','Ýstanbul Bilgi Üniversitesi','64,09');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('11','Okan Üniversitesi','61,13');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('12','Ýzmir Ekonomi Üniversitesi','60,73');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('13','Yaþar Üniversitesi','59,9');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('14','Kadir Has Üniversitesi','59,1');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('15','Çankaya Üniversitesi','58,28');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('16','Doðuþ Üniversitesi','55,72');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('17','Ýstanbul Kültür Üniversitesi','52,67');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('18','Ýstanbul Ticaret Üniversitesi','50,36');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('19','Ýstanbul Aydýn Üniversitesi','50,3');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('20','Ýstanbul Arel Üniversitesi','49,39');
Insert into UNIVERLIST.VAKIF_UNI_SIRA ("ÜNÝVERSÝTE_SIRALAMASI","VAKIF_ÜNÝVERSÝTESÝ_GENEL_SIRALAMASI","ÜNÝVERSÝTE_PUANI") values ('21','Beykent Üniversitesi','49,13');
--------------------------------------------------------
--  DDL for Index VKF_UNI_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "UNIVERLIST"."VKF_UNI_ID" ON "UNIVERLIST"."VAKIF_UNI_SIRA" ("ÜNÝVERSÝTE_SIRALAMASI") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table VAKIF_UNI_SIRA
--------------------------------------------------------

  ALTER TABLE "UNIVERLIST"."VAKIF_UNI_SIRA" MODIFY ("ÜNÝVERSÝTE_SIRALAMASI" NOT NULL ENABLE);
  ALTER TABLE "UNIVERLIST"."VAKIF_UNI_SIRA" ADD CONSTRAINT "VKF_UNI_ID" PRIMARY KEY ("ÜNÝVERSÝTE_SIRALAMASI")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
